version: '3'
services:
  app:
    build: .
    environment:
      - VIRTUAL_HOST=*.co.uk
    logging:
      options:
        max-size: 100m
    restart: always
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: 100m
    restart: always