version: '3'
services:
  app:
    build: .
    ports:
      - 80:80
    restart: always
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:
