version: '3'
services:
  app:
    build: 
      context: ./server
    ports:
      - 80:80
    restart: always
  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:
