pipeline {
    agent any

    stages {
        stage('Clone') {
            checkout scm
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'cd server/handlers && go test'
            }
        }

        stage('Deploying') {
            steps {
                echo 'Deploying...'
                sh 'docker-compose up -d --build app'
            }
        }
    }
}
