pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'docker build -t testapp server/.'
                sh 'docker run testapp -c "cd handlers/ && go test"'
                sh 'docker rmi --force $(docker images -q testapp | uniq)'
            }
        }

        stage('Deploying') {
            steps {
                echo 'Deploying...'
                sh 'docker-compose up -d --build app'
            }
        }
    }
}
