pipeline {
    agent any

    stages {
        stage('Clone') {
            checkout scm
        }

        stage('Test') {
            echo 'Testing...'
            sh 'cd server/handlers && go test'
        }

        stage('Deploying') {
            echo 'Deploying...'
            sh 'docker-compose up -d --build app'
        }
    }
}
